// Auto-generated by Device Manager — do not edit manually.
// Regenerate: curl http://localhost:5000/ci/jenkinsfile > Jenkinsfile
pipeline {
    agent any

    options {
        timeout(time: 10, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Syntax: app.py') {
            // id: syntax_app  type: syntax
            steps {
                sh 'python3 -m py_compile app.py'
            }
        }
        stage('Syntax: modules/*.py') {
            // id: syntax_modules  type: syntax_glob
            steps {
                sh 'python3 -m py_compile modules/*.py'
            }
        }
        stage('HTTP: / returns 200') {
            // id: http_root  type: http
            steps {
                sh 'curl -sf --max-time 10 http://localhost:5000/ > /dev/null'
            }
        }
        stage('HTTP: /devices returns 200') {
            // id: http_devices  type: http
            steps {
                sh 'curl -sf --max-time 10 http://localhost:5000/devices > /dev/null'
            }
        }
        stage('HTTP: /ai/providers returns 200') {
            // id: http_ai_providers  type: http
            steps {
                sh 'curl -sf --max-time 10 http://localhost:5000/ai/providers > /dev/null'
            }
        }
        stage('HTTP: /ci/jenkinsfile returns 200') {
            // id: http_ci_jenkinsfile  type: http
            steps {
                sh 'curl -sf --max-time 10 http://localhost:5000/ci/jenkinsfile > /dev/null'
            }
        }
    }

    post {
        always {
            echo "Pipeline finished: ${{currentBuild.currentResult}}"
        }
        success {
            echo 'All CI checks passed.'
        }
        failure {
            echo 'One or more CI checks FAILED — check stage output above.'
        }
    }
}
