"""Register C37: CI installs the versions the HOST runs, and the lock covers
everything the code imports.

Three environments ran three sets of versions: the laptop's system packages,
requirements.txt's pins, and the host's Ubuntu packages. A test failing on one
(C35: the pinned Flask-SocketIO 5.3.5 with python-socketio 5.10.0 drops a
Socket.IO message in the test client) was invisible until a fourth tried. The
lock is generated ON THE HOST by scripts/nmas-lock-from-host.
"""

import importlib.machinery
import importlib.util
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _script():
    path = os.path.join(ROOT, "scripts", "nmas-lock-from-host")
    loader = importlib.machinery.SourceFileLoader("nmas_lock_from_host", path)
    mod = importlib.util.module_from_spec(importlib.util.spec_from_loader(loader.name, loader))
    loader.exec_module(mod)
    return mod


def _pins():
    pins = {}
    with open(os.path.join(ROOT, "requirements.lock"), encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                name, sep, version = line.partition("==")
                assert sep and version, f"not an exact pin: {line!r}"
                pins[re.sub(r"[-_.]+", "-", name).lower()] = version
    return pins


def test_the_scan_finds_the_imports():
    imported = _script().static_imports()
    assert len(imported) >= 15, imported
    assert {"flask", "netmiko", "cryptography"} <= set(imported)


def test_every_third_party_import_is_mapped():
    lock = _script()
    unmapped = [n for n in lock.static_imports() if n not in lock.IMPORT_TO_DIST]
    assert unmapped == [], f"add to IMPORT_TO_DIST and regenerate the lock: {unmapped}"


def test_every_required_import_is_pinned_exactly():
    lock = _script()
    pins = _pins()
    assert len(pins) >= 40, len(pins)
    missing = sorted(lock.IMPORT_TO_DIST[n] for n in lock.static_imports()
                     if n not in lock.OPTIONAL
                     and re.sub(r"[-_.]+", "-", lock.IMPORT_TO_DIST[n]).lower() not in pins)
    assert missing == [], missing


def test_the_lock_names_its_producer_and_the_host():
    with open(os.path.join(ROOT, "requirements.lock"), encoding="utf-8") as fh:
        head = fh.read(600)
    assert "Generated by scripts/nmas-lock-from-host on the host" in head


def test_the_pair_that_dropped_a_message_is_not_what_ci_installs():
    """C35: the lock is the host's pair, never requirements.txt's."""
    pins = _pins()
    assert pins["flask-socketio"] == "5.3.6" and pins["python-socketio"] == "5.7.2"
