"""Register C37: CI installs the versions the HOST runs, and the lock covers
everything the code imports.

Three environments ran three sets of versions: the laptop's system packages,
requirements.txt's pins, and the host's Ubuntu packages. A test failing on one
(C35: the pinned Flask-SocketIO 5.3.5 with python-socketio 5.10.0 drops a
Socket.IO message in the test client) was invisible until a fourth tried. The
lock is generated ON THE HOST by scripts/nmas-lock-from-host.
"""

import importlib.machinery
import importlib.util
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _script():
    path = os.path.join(ROOT, "scripts", "nmas-lock-from-host")
    loader = importlib.machinery.SourceFileLoader("nmas_lock_from_host", path)
    mod = importlib.util.module_from_spec(importlib.util.spec_from_loader(loader.name, loader))
    loader.exec_module(mod)
    return mod


def _pins():
    pins = {}
    with open(os.path.join(ROOT, "requirements.lock"), encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                name, sep, version = line.partition("==")
                assert sep and version, f"not an exact pin: {line!r}"
                pins[re.sub(r"[-_.]+", "-", name).lower()] = version
    return pins


def test_the_scan_finds_the_imports():
    imported = _script().static_imports()
    assert len(imported) >= 15, imported
    assert {"flask", "netmiko", "cryptography"} <= set(imported)


def test_every_third_party_import_is_mapped():
    lock = _script()
    unmapped = [n for n in lock.static_imports() if n not in lock.IMPORT_TO_DIST]
    assert unmapped == [], f"add to IMPORT_TO_DIST and regenerate the lock: {unmapped}"


def test_every_required_import_is_pinned_exactly():
    lock = _script()
    pins = _pins()
    assert len(pins) >= 40, len(pins)
    missing = sorted(lock.IMPORT_TO_DIST[n] for n in lock.static_imports()
                     if n not in lock.OPTIONAL
                     and re.sub(r"[-_.]+", "-", lock.IMPORT_TO_DIST[n]).lower() not in pins)
    assert missing == [], missing


def test_the_lock_names_its_producer_and_the_host():
    with open(os.path.join(ROOT, "requirements.lock"), encoding="utf-8") as fh:
        head = fh.read(600)
    assert "Generated by scripts/nmas-lock-from-host on the host" in head


def test_the_pair_that_dropped_a_message_is_not_what_ci_installs():
    """C35: the lock is the host's pair, never requirements.txt's."""
    pins = _pins()
    assert pins["flask-socketio"] == "5.3.6" and pins["python-socketio"] == "5.7.2"


# Captured from `systemctl show -p ExecStart --value flask-app.service` on the host (2026-10-09),
# the checkout's path replaced; the venv's line is the same unit after Phase 4 section 8's switch.
SYSTEM_EXECSTART = ("{ path=/usr/bin/python3 ; argv[]=/usr/bin/python3 <checkout>/app.py ; "
                    "ignore_errors=no ; start_time=[Fri 2026-10-09 04:44:34 UTC] ; "
                    "stop_time=[n/a] ; pid=255576 ; code=(null) ; status=0/0 }")
VENV_EXECSTART = SYSTEM_EXECSTART.replace("/usr/bin/python3", "/opt/mercury-venv/bin/python")


def test_the_lock_is_read_by_the_interpreter_the_app_runs():
    """Phase 4 section 8 (the operator, 2026-10-09): after the switch the lock must be read from
    the venv, so the script re-runs itself under flask-app's interpreter, whichever ran it."""
    lock = _script()
    assert lock.app_interpreter(SYSTEM_EXECSTART) == ("/usr/bin/python3", "")
    assert lock.app_interpreter(VENV_EXECSTART) == ("/opt/mercury-venv/bin/python", "")
    # Started by a login shell's python3 before the switch, or the venv's after it: no re-run.
    assert lock.interpreter_to_read("/usr/bin/python3", "/usr") is None
    assert lock.interpreter_to_read("/opt/mercury-venv/bin/python", "/opt/mercury-venv") is None
    # Started by /usr/bin/python3 after the switch: re-run under the venv's.
    assert (lock.interpreter_to_read("/opt/mercury-venv/bin/python", "/usr")
            == "/opt/mercury-venv/bin/python")
    # And the reverse, the venv's python3 after a rollback: re-run under the system's.
    assert lock.interpreter_to_read("/usr/bin/python3", "/opt/mercury-venv") == "/usr/bin/python3"


def test_a_machine_without_the_unit_says_which_interpreter_it_read():
    path, why = _script().app_interpreter("")
    assert path is None and "flask-app.service" in why
