"""A regenerated self-signed certificate is drawn as one labelled line, never
as its hex (the operator, 2026-10-01: after the afternoon's redeploy the Save
All preview showed r1, r2 and r4 differing by certificate only, 49 lines of
hex where the one thing to know is that the device made a new one at boot).

On r2's REAL configuration, its certificate regenerated by a minimal edit (a
new chassis-derived trustpoint name and one changed hex word, which is what a
boot produces): the capture preview and drift each carry the line
``~ regenerated self-signed certificate (expected after a boot): ...`` and no
hex; drift does not count it as drift; a CA-signed trustpoint is never folded;
and the golden is still recorded VERBATIM, certificate and all.
"""

import subprocess

import pytest

from modules.nsot.normalize import CERT_REGENERATED, self_signed_note
from tests.test_capture import _apply, _hash, _preview, build_capture_lab
from tests.test_intent_match import R2

OLD = "TP-self-signed-2968666059"
NEW = "TP-self-signed-1207741302"


def _regenerated(text):
    """r2's config as it comes back from a boot: a new name, a new body."""
    assert text.count(OLD) == 3 and "30820330 30820218" in text
    return text.replace("2968666059", "1207741302").replace("30820330 30820218",
                                                              "30820331 30820219")


def _hex_lines(lines):
    return [l for l in lines if l.lstrip("+- ").startswith("3082")]


class TestTheNote:
    def test_the_same_certificate_says_nothing(self):
        r2 = open(R2, encoding="utf-8").read()
        assert self_signed_note(r2, r2) == ""

    def test_a_regenerated_certificate_is_one_line_naming_both(self):
        r2 = open(R2, encoding="utf-8").read()
        note = self_signed_note(r2, _regenerated(r2))
        assert note.startswith(f"~ {CERT_REGENERATED}: {OLD} -> {NEW};")
        assert "recorded verbatim, not drawn" in note

    def test_a_body_change_under_the_same_name_is_said(self):
        r2 = open(R2, encoding="utf-8").read()
        after = r2.replace("30820330 30820218", "30820331 30820219")
        assert f"{OLD}, its body changed" in self_signed_note(r2, after)

    def test_a_ca_signed_trustpoint_is_never_folded(self):
        # SLA-TrustPoint is r2's own CA-signed trustpoint: configuration somebody
        # chose, so a change to it is drift and draws as lines.
        r2 = open(R2, encoding="utf-8").read()
        assert "crypto pki trustpoint SLA-TrustPoint" in r2
        after = r2.replace("crypto pki trustpoint SLA-TrustPoint",
                           "crypto pki trustpoint SLA-TrustPoint-2")
        assert self_signed_note(r2, after) == ""


@pytest.fixture
def cap(tmp_path, monkeypatch):
    return build_capture_lab(monkeypatch, tmp_path)


class TestTheCapturePreview:
    def test_the_certificate_is_one_labelled_line_and_no_hex(self, cap):
        cap["running"]["r2"] = _regenerated(cap["captured"])
        d = _preview(cap)
        target = d["preview"]["what"]["targets"][0]
        assert target["state"] == "capturable"
        lines = d["preview"]["targets"][0]["program"]["lines"]
        assert any(l.startswith(f"~ {CERT_REGENERATED}: {OLD} -> {NEW}") for l in lines), lines
        assert _hex_lines(lines) == [], _hex_lines(lines)[:3]
        assert not any(OLD in l and l.startswith(("+", "-")) for l in lines)

    def test_another_change_is_still_drawn_beside_it(self, cap):
        cap["running"]["r2"] = _regenerated(cap["captured"]).replace(
            "hostname r2\n", "hostname r2\nip domain lookup source-interface Loopback0\n")
        lines = _preview(cap)["preview"]["targets"][0]["program"]["lines"]
        assert "+ip domain lookup source-interface Loopback0" in lines
        assert any(l.startswith(f"~ {CERT_REGENERATED}") for l in lines)

    def test_the_golden_is_recorded_verbatim(self, cap):
        cap["running"]["r2"] = _regenerated(cap["captured"])
        d = _preview(cap)
        _apply(cap, {"r2": _hash(d)})
        golden = subprocess.run(["git", "-C", cap["repo"], "show", "HEAD:golden/r2.cfg"],
                                capture_output=True, text=True).stdout
        assert f"crypto pki certificate chain {NEW}" in golden
        assert "30820331 30820219" in golden


@pytest.fixture
def drift(monkeypatch):
    from modules import drift_check

    r2 = open(R2, encoding="utf-8").read()
    devices = [{"hostname": "r2", "ip": "203.0.113.12", "username": "u", "password": "p",
                "device_type": "cisco_xe"}]
    golden = {"203.0.113.12": r2}
    running = {"203.0.113.12": _regenerated(r2)}
    queued = []
    monkeypatch.setattr("modules.device.get_current_device_list", lambda: ("lab", "lab.csv"))
    monkeypatch.setattr("modules.device.load_saved_devices", lambda path: list(devices))
    monkeypatch.setattr("modules.ai_assistant._golden_record",
                        lambda ip: {"text": golden.get(ip), "path": "", "commit": "",
                                    "source": "", "refused": ""})
    monkeypatch.setattr("modules.connection.get_persistent_connection",
                        lambda dev, pool, lock: dev["ip"])
    monkeypatch.setattr("modules.commands.run_device_command", lambda conn, cmd: running[conn])
    monkeypatch.setattr("modules.approval_queue.add_approval",
                        lambda **kw: queued.append(kw) or {"ok": True})
    return {"module": drift_check, "running": running, "queued": queued, "r2": r2}


class TestDrift:
    def test_a_certificate_alone_is_not_drift_and_is_said(self, drift):
        r = drift["module"].run_drift_check("test")
        assert r["drifted"] == 0 and r["clean"] == 1, r["summary"]
        assert drift["queued"] == []
        assert "Regenerated self-signed certificate (expected after a boot), not drift: r2." \
            in r["summary"]

    def test_with_real_drift_the_queued_diff_carries_the_label_not_the_hex(self, drift):
        drift["running"]["203.0.113.12"] = _regenerated(drift["r2"]).replace(
            "hostname r2\n", "hostname r2\nip domain lookup source-interface Loopback0\n")
        r = drift["module"].run_drift_check("test")
        assert r["drifted"] == 1
        diff = drift["queued"][0]["diff"].splitlines()
        assert "+ip domain lookup source-interface Loopback0" in diff
        assert any(l.startswith(f"~ {CERT_REGENERATED}") for l in diff)
        assert _hex_lines(diff) == []

    def test_the_same_certificate_draws_no_note(self, drift):
        drift["running"]["203.0.113.12"] = drift["r2"]
        r = drift["module"].run_drift_check("test")
        assert r["clean"] == 1 and CERT_REGENERATED not in r["summary"].lower()
